version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 120
      runas: root
