version: 0.0
os: linux
files:
  - source: /
    destination: /agrijod-backend
hooks:
  AfterInstall:
    - location: install_dependencies.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 120
      runas: root
  AfterAllowTraffic:
    - location: health_check.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 120
      runas: root
