name: AWS CD Pipeline
on:
  push:
    branches: [main, Deployment]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/Deployment'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name agrizod_backend_alpha \
            --deployment-group-name agrijod_backend_deployment_alpha \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --file-exists-behavior OVERWRITE

      - name: Check Deployment Status
        run: |
          STATUS=$(aws deploy get-deployment --deployment-id ${{ steps.deploy.outputs.deployment-id }} --query "deploymentInfo.status" --output text)
          echo "Deployment status: $STATUS"
          if [ $STATUS == "Failed" ]; then
            exit 1
          fi
