name: AWS CD Pipeline
on:
  push:
    branches: [ main, Deployment ]
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  ci-output-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check CI output and exit if failed
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" == "failure" ]; then
            echo "CI failed, exiting..."
            exit 1
          fi

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: ci-output-check
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/Deployment'
    steps:
      # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name agrizod_backend_alpha \
            --deployment-group-name agrijod_backend_deployment_alpha \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --file-exists-behavior OVERWRITE
