# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "Deployment" ]
  pull_request:
    branches: [ "main", "Deployment" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ESLint check
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: npm install eslint
      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install --save-dev && npm ci
    - name: Start server and Run a Deep Health Check post timeout
      run: |
        npm run start &
        sleep 10
        # Health check and exit with an error if response is not 200
        if [ $(curl -s -I -o /dev/null -w '%{http_code}' http://localhost:8000/actuator/health/deep) != "200" ];
        then
          echo "Health check failed"
          exit 1
        else
          echo "Health check passed"
        fi

